nelmio_api_doc:
    sandbox:
        accept_type:        'application/json'
        body_format:
            formats:        ['json']
            default_format: 'json'
        request_format:
            formats:
                json:       'application/json'
        authentication:
            name:           authorization
            delivery:       http
            type:           bearer