services:
    arena.query_extension.not_expired:
        class: AppBundle\Doctrine\ORM\Extension\NotExpiredExtension
        public: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item, priority: 9 }